### ISSUE TITLE
Verify Fallback Fonts in Design Tokens and Update Storybook Documentation

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#547]
### Description:

As part of our ongoing efforts to support multiple languages in MetaMask, we need to ensure that our typography is accessible and legible across all translations. Currently, our primary font, Euclid Circular, does not support all translated languages (e.g., Hindi). 

Fallback fonts for Euclid are currently used in the extension:
```
font-family: 'Euclid Circular B', Roboto, Helvetica, Arial, sans-serif;
```
We need to verify that these fallback fonts are defined in the design tokens code and update the Storybook documentation accordingly.

### Tasks:
- [ ] Check that the fallback fonts are defined in the design tokens code
- [ ] Update the Storybook documentation to include the fallback fonts 
![Screenshot 2023-12-07 at 10 34 10 AM](https://github.com/MetaMask/design-tokens/assets/8112138/127d2ced-a405-4dfb-bd71-8f34136c14ea)
- [ ] Review and test the documentation updates

### Acceptance Criteria:
- The fallback fonts are confirmed to be in the design tokens code
- The Storybook documentation is updated to include the fallback fonts
- The documentation updates are reviewed and tested
